### PR TITLE
docs: re-organize app builder configuration section and add required products

### PR DESCRIPTION
**Pull request by MichaelGoberling**
## Description

- (new) `App Builder Configuration`
- (new) `App Builder Configuration > Required Products`
- (modify) `Custom Configuration` to `App Builder Configuration > Customer Configuration` 

TODO: How do we help customers find product codes and their supported versions?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MichaelGoberling** [comment]
Fixed the broken link to customer configuration in discoverageandmanage.md, but it seems I also broke links on other pages that link to customer configuration, but are actually supposed to link to an FAQ page? https://github.com/AdobeDocs/Developer-Distribution-Experience-Cloud/actions/runs/9520489678/job/26245898590?pr=15#step:11:19

I don't see an FAQ page in this repo, is it supposed to be an external link?

**Review by purplecabbage — APPROVED** [review]
Should we remove that **todo**

**Comment by MichaelGoberling** [comment]
Making this a draft for now while we discuss re-organization ISV documentation as a whole

**Comment by MichaelGoberling** [comment]
Closing this as we've planned to go a different direction and move all App Builder configuration details to the [App Builder docs](https://developer.adobe.com/app-builder/docs/overview/)

**Pull request closed without merging**
